# Generated by Django 4.2.3 on 2023-07-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('domain_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxa_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clade', models.CharField(blank=True, max_length=1, null=True)),
                ('genus', models.CharField(blank=True, max_length=256, null=True)),
                ('species', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('sequence', models.TextField(blank=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('domains', models.ManyToManyField(null=True, to='protein_data.pfam')),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein_data.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_data.pfam')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains_in_protein', to='protein_data.protein')),
            ],
        ),
    ]
