# Generated by Django 4.2.3 on 2023-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_data', '0002_remove_domain_protein_remove_protein_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='domains',
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(null=True, to='protein_data.domain'),
        ),
    ]
